### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by CsatiZoltan** [jlblancoc/openbeam#1]
I built it successfully on Linux. I started OpenBeamStudio, loaded one of the examples, but what to do next? The text file appeared on the right panel but I cannot run an analysis.

**Comment by jlblancoc** [comment]
Hi @CsatiZoltan 
Unfortunately, the GUI OpenBeamStudio is one of those projects I started so often and then realize have no time to fully implement due to other projects being far more urgent for me.

In short: don't use the GUI OpenBeamStudio. 
Instead, you can use the command line app `ob-solver`.

For example, [this input file](https://github.com/jlblancoc/openbeam/blob/master/examples-structures/pr1_05.txt) has a comment with an example of the full command line required to generate an HTML output, plots, etc. 

Hope it helps!

PS: Any contribution to this project (report, pull-requests,..) will be more than welcome!

**Comment by jlblancoc** [comment]
I forgot: if you want to generate animations, only Linux is supported for now... 

HTML output, plots, etc. work in any OS.
